CREATE SCHEMA catalogoDeProductos;

USE catalogoDeProductos;

CREATE TABLE usuarios (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(200) NOT NULL UNIQUE,
usuario VARCHAR(200) NOT NULL UNIQUE,
contrasena VARCHAR(200) NOT NULL,
fechaNacimiento DATE NOT NULL,
documento INT NOT NULL UNIQUE,
fotoPerfil VARCHAR(250),
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP NULL
);

CREATE TABLE productos (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
usuarios_id INT UNSIGNED,
nombreProducto VARCHAR(200) NOT NULL,
descripcion VARCHAR(1000),
imagen VARCHAR(250),

createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP NULL,

FOREIGN KEY (usuarios_id) REFERENCES usuarios(id)

);

CREATE TABLE comentarios (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
productos_id INT UNSIGNED,
usuarios_id INT UNSIGNED,
texto VARCHAR(600),

createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP NULL,

FOREIGN KEY (usuarios_id) REFERENCES usuarios(id),
FOREIGN KEY (productos_id) REFERENCES productos(id)

);





